### ISSUE TITLE
UploadEntity.java:146-148: Add unit tests for...

### ISSUE THREAD

**Issue by 0pdd** [artipie/docker-adapter#99] opened 2020-04-29 15:59 UTC
The puzzle `54-cd653684` from #54 has to be resolved: 

https://github.com/artipie/docker-adapter/blob/60af487a84be8a75f0f441b25718884c8029b848/src/main/java/com/artipie/docker/http/UploadEntity.java#L146-L148

The puzzle was created by @olegmoz on 29-Apr-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment] 2020-04-29 16:00
@g4s8[/z](https://www.0crat.com/u/g4s8) please, pay attention to this issue

**Comment by 0crat** [comment] 2020-04-29 17:46
The job [#99](https://github.com/artipie/docker-adapter/issues/99) assigned to @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/ca1cff1f-6fdb-4e02-9722-cd5192a4546f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-04-29 17:48
Job [#99](https://github.com/artipie/docker-adapter/issues/99) is not in the agenda of @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda), can't set title

**Comment by carlosmiranda** [comment] 2020-04-30 03:45
@0crat refuse

**Comment by 0crat** [comment] 2020-04-30 03:45
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-1398-thread-1
com.zerocracy.radars.github.ReSafe[81] java.io.IOException: java.lang.OutOfMemoryError: unable to create new native thread
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.13](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#99, Action: `created`

**Comment by 0crat** [comment] 2020-04-30 03:46
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/farm/issues):

```
PID: 4@4ea0ebc5-1e90-4d29-b5a1-8c93eef19bcd, thread: pool-1399-thread-1
java.lang.Thread[-2] java.lang.OutOfMemoryError: unable to create new native thread
```

[0.53.13](https://github.com/zerocracy/farm): Issue: artipie/docker-adapter#99, Comment: 621595353

**Comment by carlosmiranda** [comment] 2020-04-30 03:46
@0crat refuse

**Comment by 0crat** [comment] 2020-04-30 03:52
> @0crat refuse ([here](https://github.com/artipie/docker-adapter/issues/99#issuecomment-621595509))

@carlosmiranda The user @carlosmiranda[/z](https://www.0crat.com/u/carlosmiranda) resigned from [#99](https://github.com/artipie/docker-adapter/issues/99), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment] 2020-04-30 03:52
> @0crat refuse ([here](https://github.com/artipie/docker-adapter/issues/99#issuecomment-621595509))

@carlosmiranda Job refused in 10 hours - no penalty, see [§6](http://www.zerocracy.com/policy.html#6)

**Comment by 0crat** [comment] 2020-04-30 17:46
The job [#99](https://github.com/artipie/docker-adapter/issues/99) assigned to @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), here is [why](https://www.0crat.com/footprint/CT2E6TK9B/e244c6cf-9d0e-46a6-9432-caa59fc101dc); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be a monetary reward for this job

**Comment by 0crat** [comment] 2020-05-05 18:45
@ammaratef45[/z](https://www.0crat.com/u/ammaratef45) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Closed** 2020-05-20 15:40 UTC
Labels: bug, pdd, role/DEV, scope

**Comment by 0crat** [comment] 2020-05-20 16:06
@olegmoz[/z](https://www.0crat.com/u/olegmoz) the issue is closed not by @0pdd[/z](https://www.0crat.com/u/0pdd) (its creator); I won't close the order; please, re-open it and ask @0pdd[/z](https://www.0crat.com/u/0pdd) to close it

**Comment by g4s8** [comment] 2020-05-21 06:24
@0crat out

**Comment by 0crat** [comment] 2020-05-21 06:26
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @ammaratef45[/z](https://www.0crat.com/u/ammaratef45), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

**Comment by sereshqua** [comment] 2020-05-21 06:29
@g4s8 I am wondering why I am evaluating @ammaratef45 NOT @olegmoz ? Should the quality be bad for @ammaratef45?

**Comment by g4s8** [comment] 2020-05-21 06:31
@sereshqua I think yes

**Comment by sereshqua** [comment] 2020-05-21 06:35
@0crat quality bad

**Comment by 0crat** [comment] 2020-05-21 06:45
Quality is low, no payment, see [§31](http://www.zerocracy.com/policy.html#31)
